### ISSUE TITLE
publish to npm

### ISSUE THREAD

**Issue by guumaster** [fp-dom/fd-listen#1]
This should have been a PR, but I previously had the repo checked out as upstream/master and made the wrong push to upstream instead of my fork. Sorry about that. 

With that said, if you are ok with the changed introduced in the [last two commits](https://github.com/fp-dom/fd-listen/compare/1581938cfe4c628d80decf0126f96c2d6f6e76ef...master)*, you may update the npm package or grant me access to update it.
- changed 6to5 to babel and changed `6to5/polyfill` to `core-js/shim` to fix error on `fp-dom` build script.

**Comment by stoeffel** [comment]
I'm not in front of a computer atm, but I will add you as a npm owner asab. Or maybe @hemanth is quicker.

**Comment by guumaster** [comment]
cool, without this changes  `fp-dom` is broken at the moment.

**Comment by hemanth** [comment]
I was away too, @guumaster you need ownership over `fp-dom`?

**Comment by guumaster** [comment]
I can update/publish `fp-dom`. This repo, `fd-listen`, is the one that should be updated in npm.

**Comment by hemanth** [comment]
```
$ npm owner add guumaster fd-listen
+ guumaster (fd-listen)
```

**Comment by guumaster** [comment]
excelent
